// ============================================================
// PhysicClaw-VEA — boneMaps
// Bone name → standard rig name mappings for animation retargeting.
// Each map translates a rig-specific bone name to the canonical
// THREE.SkeletonUtils.retargetClip target name.
// ============================================================
import type { RigType } from './constraints'

export type { RigType }

/**
 * Maps source bone names (rig-specific) to target bone names (standard skeleton).
 * Used by THREE.SkeletonUtils.retargetClip to align animation clips.
 */
export const BONE_MAPS: Record<RigType, Record<string, string>> = {
    mixamo: {
        'mixamorig:Hips': 'Hips',
        'mixamorig:Spine': 'Spine',
        'mixamorig:Spine1': 'Spine1',
        'mixamorig:Spine2': 'Spine2',
        'mixamorig:Neck': 'Neck',
        'mixamorig:Head': 'Head',
        'mixamorig:HeadTop_End': 'HeadTop_End',
        'mixamorig:LeftEye': 'LeftEye',
        'mixamorig:RightEye': 'RightEye',
        'mixamorig:LeftShoulder': 'LeftShoulder',
        'mixamorig:LeftArm': 'LeftArm',
        'mixamorig:LeftForeArm': 'LeftForeArm',
        'mixamorig:LeftHand': 'LeftHand',
        'mixamorig:LeftHandThumb1': 'LeftHandThumb1',
        'mixamorig:LeftHandThumb2': 'LeftHandThumb2',
        'mixamorig:LeftHandThumb3': 'LeftHandThumb3',
        'mixamorig:LeftHandIndex1': 'LeftHandIndex1',
        'mixamorig:LeftHandIndex2': 'LeftHandIndex2',
        'mixamorig:LeftHandIndex3': 'LeftHandIndex3',
        'mixamorig:LeftHandMiddle1': 'LeftHandMiddle1',
        'mixamorig:LeftHandMiddle2': 'LeftHandMiddle2',
        'mixamorig:LeftHandMiddle3': 'LeftHandMiddle3',
        'mixamorig:LeftHandRing1': 'LeftHandRing1',
        'mixamorig:LeftHandRing2': 'LeftHandRing2',
        'mixamorig:LeftHandRing3': 'LeftHandRing3',
        'mixamorig:LeftHandPinky1': 'LeftHandPinky1',
        'mixamorig:LeftHandPinky2': 'LeftHandPinky2',
        'mixamorig:LeftHandPinky3': 'LeftHandPinky3',
        'mixamorig:RightShoulder': 'RightShoulder',
        'mixamorig:RightArm': 'RightArm',
        'mixamorig:RightForeArm': 'RightForeArm',
        'mixamorig:RightHand': 'RightHand',
        'mixamorig:RightHandThumb1': 'RightHandThumb1',
        'mixamorig:RightHandThumb2': 'RightHandThumb2',
        'mixamorig:RightHandThumb3': 'RightHandThumb3',
        'mixamorig:RightHandIndex1': 'RightHandIndex1',
        'mixamorig:RightHandIndex2': 'RightHandIndex2',
        'mixamorig:RightHandIndex3': 'RightHandIndex3',
        'mixamorig:RightHandMiddle1': 'RightHandMiddle1',
        'mixamorig:RightHandMiddle2': 'RightHandMiddle2',
        'mixamorig:RightHandMiddle3': 'RightHandMiddle3',
        'mixamorig:RightHandRing1': 'RightHandRing1',
        'mixamorig:RightHandRing2': 'RightHandRing2',
        'mixamorig:RightHandRing3': 'RightHandRing3',
        'mixamorig:RightHandPinky1': 'RightHandPinky1',
        'mixamorig:RightHandPinky2': 'RightHandPinky2',
        'mixamorig:RightHandPinky3': 'RightHandPinky3',
        'mixamorig:LeftUpLeg': 'LeftUpLeg',
        'mixamorig:LeftLeg': 'LeftLeg',
        'mixamorig:LeftFoot': 'LeftFoot',
        'mixamorig:LeftToeBase': 'LeftToeBase',
        'mixamorig:RightUpLeg': 'RightUpLeg',
        'mixamorig:RightLeg': 'RightLeg',
        'mixamorig:RightFoot': 'RightFoot',
        'mixamorig:RightToeBase': 'RightToeBase',
    },

    // ReadyPlayerMe uses standard humanoid bone names (close to the Unity Humanoid rig)
    rpm: {
        Hips: 'Hips',
        Spine: 'Spine',
        Spine1: 'Spine1',
        Spine2: 'Spine2',
        Neck: 'Neck',
        Head: 'Head',
        LeftShoulder: 'LeftShoulder',
        LeftArm: 'LeftArm',
        LeftForeArm: 'LeftForeArm',
        LeftHand: 'LeftHand',
        LeftHandThumb1: 'LeftHandThumb1',
        LeftHandThumb2: 'LeftHandThumb2',
        LeftHandThumb3: 'LeftHandThumb3',
        LeftHandIndex1: 'LeftHandIndex1',
        LeftHandIndex2: 'LeftHandIndex2',
        LeftHandIndex3: 'LeftHandIndex3',
        LeftHandMiddle1: 'LeftHandMiddle1',
        LeftHandMiddle2: 'LeftHandMiddle2',
        LeftHandMiddle3: 'LeftHandMiddle3',
        LeftHandRing1: 'LeftHandRing1',
        LeftHandRing2: 'LeftHandRing2',
        LeftHandRing3: 'LeftHandRing3',
        LeftHandPinky1: 'LeftHandPinky1',
        LeftHandPinky2: 'LeftHandPinky2',
        LeftHandPinky3: 'LeftHandPinky3',
        RightShoulder: 'RightShoulder',
        RightArm: 'RightArm',
        RightForeArm: 'RightForeArm',
        RightHand: 'RightHand',
        RightHandThumb1: 'RightHandThumb1',
        RightHandThumb2: 'RightHandThumb2',
        RightHandThumb3: 'RightHandThumb3',
        RightHandIndex1: 'RightHandIndex1',
        RightHandIndex2: 'RightHandIndex2',
        RightHandIndex3: 'RightHandIndex3',
        RightHandMiddle1: 'RightHandMiddle1',
        RightHandMiddle2: 'RightHandMiddle2',
        RightHandMiddle3: 'RightHandMiddle3',
        RightHandRing1: 'RightHandRing1',
        RightHandRing2: 'RightHandRing2',
        RightHandRing3: 'RightHandRing3',
        RightHandPinky1: 'RightHandPinky1',
        RightHandPinky2: 'RightHandPinky2',
        RightHandPinky3: 'RightHandPinky3',
        LeftUpLeg: 'LeftUpLeg',
        LeftLeg: 'LeftLeg',
        LeftFoot: 'LeftFoot',
        LeftToeBase: 'LeftToeBase',
        RightUpLeg: 'RightUpLeg',
        RightLeg: 'RightLeg',
        RightFoot: 'RightFoot',
        RightToeBase: 'RightToeBase',
    },

    // VRM 0.x/1.x uses J_Bip_C_* (center) and J_Bip_L_*/J_Bip_R_* naming convention
    vrm: {
        J_Bip_C_Hips: 'Hips',
        J_Bip_C_Spine: 'Spine',
        J_Bip_C_Chest: 'Spine1',
        J_Bip_C_UpperChest: 'Spine2',
        J_Bip_C_Neck: 'Neck',
        J_Bip_C_Head: 'Head',
        J_Bip_L_Shoulder: 'LeftShoulder',
        J_Bip_L_UpperArm: 'LeftArm',
        J_Bip_L_LowerArm: 'LeftForeArm',
        J_Bip_L_Hand: 'LeftHand',
        J_Bip_L_Thumb1: 'LeftHandThumb1',
        J_Bip_L_Thumb2: 'LeftHandThumb2',
        J_Bip_L_Thumb3: 'LeftHandThumb3',
        J_Bip_L_Index1: 'LeftHandIndex1',
        J_Bip_L_Index2: 'LeftHandIndex2',
        J_Bip_L_Index3: 'LeftHandIndex3',
        J_Bip_L_Middle1: 'LeftHandMiddle1',
        J_Bip_L_Middle2: 'LeftHandMiddle2',
        J_Bip_L_Middle3: 'LeftHandMiddle3',
        J_Bip_L_Ring1: 'LeftHandRing1',
        J_Bip_L_Ring2: 'LeftHandRing2',
        J_Bip_L_Ring3: 'LeftHandRing3',
        J_Bip_L_Little1: 'LeftHandPinky1',
        J_Bip_L_Little2: 'LeftHandPinky2',
        J_Bip_L_Little3: 'LeftHandPinky3',
        J_Bip_R_Shoulder: 'RightShoulder',
        J_Bip_R_UpperArm: 'RightArm',
        J_Bip_R_LowerArm: 'RightForeArm',
        J_Bip_R_Hand: 'RightHand',
        J_Bip_R_Thumb1: 'RightHandThumb1',
        J_Bip_R_Thumb2: 'RightHandThumb2',
        J_Bip_R_Thumb3: 'RightHandThumb3',
        J_Bip_R_Index1: 'RightHandIndex1',
        J_Bip_R_Index2: 'RightHandIndex2',
        J_Bip_R_Index3: 'RightHandIndex3',
        J_Bip_R_Middle1: 'RightHandMiddle1',
        J_Bip_R_Middle2: 'RightHandMiddle2',
        J_Bip_R_Middle3: 'RightHandMiddle3',
        J_Bip_R_Ring1: 'RightHandRing1',
        J_Bip_R_Ring2: 'RightHandRing2',
        J_Bip_R_Ring3: 'RightHandRing3',
        J_Bip_R_Little1: 'RightHandPinky1',
        J_Bip_R_Little2: 'RightHandPinky2',
        J_Bip_R_Little3: 'RightHandPinky3',
        J_Bip_L_UpperLeg: 'LeftUpLeg',
        J_Bip_L_LowerLeg: 'LeftLeg',
        J_Bip_L_Foot: 'LeftFoot',
        J_Bip_L_ToeBase: 'LeftToeBase',
        J_Bip_R_UpperLeg: 'RightUpLeg',
        J_Bip_R_LowerLeg: 'RightLeg',
        J_Bip_R_Foot: 'RightFoot',
        J_Bip_R_ToeBase: 'RightToeBase',
    },

    // Standard / generic rig (Unity Humanoid / BVH convention — bones already named canonically)
    standard: {
        Hips: 'Hips',
        Spine: 'Spine',
        Spine1: 'Spine1',
        Spine2: 'Spine2',
        Neck: 'Neck',
        Head: 'Head',
        LeftShoulder: 'LeftShoulder',
        LeftArm: 'LeftArm',
        LeftForeArm: 'LeftForeArm',
        LeftHand: 'LeftHand',
        RightShoulder: 'RightShoulder',
        RightArm: 'RightArm',
        RightForeArm: 'RightForeArm',
        RightHand: 'RightHand',
        LeftUpLeg: 'LeftUpLeg',
        LeftLeg: 'LeftLeg',
        LeftFoot: 'LeftFoot',
        LeftToeBase: 'LeftToeBase',
        RightUpLeg: 'RightUpLeg',
        RightLeg: 'RightLeg',
        RightFoot: 'RightFoot',
        RightToeBase: 'RightToeBase',
    },
}
