import { defineConfig, Plugin, ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'
import obfuscatorPlugin from 'vite-plugin-javascript-obfuscator'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

// Origins allowed to POST to /api/control. Extend as needed.
const VITE_PORT = Number(process.env.VITE_PORT ?? 5173)
const ALLOWED_ORIGINS = [
    `http://localhost:${VITE_PORT}`,
    `http://127.0.0.1:${VITE_PORT}`,
]

// Secret token for /api/control. Set CONTROL_API_TOKEN in your shell before
// starting the dev server. Falls back to a random token so the endpoint is
// never accidentally open with an empty secret.
const CONTROL_API_TOKEN =
    process.env.CONTROL_API_TOKEN ??
    (() => {
        const random = crypto.randomBytes(16).toString('hex')
        console.warn('[openclaw-control] CONTROL_API_TOKEN not set. Using auto-generated secure token for this session.')
        return random
    })()

// Port where OpenClaw / local LLM proxy is listening.
// Override via OPENCLAW_LOCAL_PORT env var.
const OPENCLAW_LOCAL_PORT = Number(process.env.OPENCLAW_LOCAL_PORT ?? 18789)


// Allowed commands and their value validators
const COMMAND_VALIDATORS: Record<string, (v: unknown) => boolean> = {
    setMood: v => typeof v === 'string' && ['calm', 'excited', 'thinking', 'listening'].includes(v),
    setIsThinking: v => typeof v === 'boolean',
    setIntensity: v => typeof v === 'number' && v >= 0 && v <= 2,
    setLastMessage: v => typeof v === 'string' && v.length <= 500,
    setActiveCharacterId: v => typeof v === 'string' && v.length > 0 && v.length <= 64,
}

// Simple in-memory rate limiter: max 30 requests per minute per IP
const rateLimitMap = new Map<string, { count: number; resetAt: number }>()
const RATE_LIMIT = 30
const RATE_WINDOW_MS = 60_000

function isRateLimited(ip: string): boolean {
    const now = Date.now()
    const entry = rateLimitMap.get(ip)
    if (!entry || now > entry.resetAt) {
        rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_WINDOW_MS })
        return false
    }
    entry.count++
    return entry.count > RATE_LIMIT
}

function openClawControlPlugin(): Plugin {
    let lastProcessedId: string | null = null

    function broadcast(server: ViteDevServer, command: Record<string, unknown>) {
        const id = String(command.id ?? '')
        if (id && id === lastProcessedId) return
        lastProcessedId = id
        server.ws.send({ type: 'custom', event: 'openclaw-command', data: command })
    }

    return {
        name: 'openclaw-control',
        configureServer(server) {
            const controlFile = path.resolve(process.cwd(), 'openclaw-control.json')
            const tokenFilePath = path.resolve(process.cwd(), '.openclaw-token')

            // Write token to file and show console warning if it was autogenerated
            if (!process.env.CONTROL_API_TOKEN) {
                console.log('\n┌────────────────────────────────────────────────────────┐');
                console.log('│ [openclaw-control] CONTROL_API_TOKEN autogenerado:     │');
                console.log(`│ ${CONTROL_API_TOKEN.padEnd(54, ' ')} │`);
                console.log('└────────────────────────────────────────────────────────┘\n');
                
                try {
                    fs.writeFileSync(tokenFilePath, CONTROL_API_TOKEN, 'utf-8')
                    
                    // Automatically ensure .openclaw-token is in .gitignore
                    const gitignorePath = path.resolve(process.cwd(), '.gitignore')
                    if (fs.existsSync(gitignorePath)) {
                        const content = fs.readFileSync(gitignorePath, 'utf-8')
                        if (!content.includes('.openclaw-token')) {
                            const newContent = content.endsWith('\n') 
                                ? content + '# OpenClaw Dev Token\n.openclaw-token\n' 
                                : content + '\n\n# OpenClaw Dev Token\n.openclaw-token\n'
                            fs.writeFileSync(gitignorePath, newContent, 'utf-8')
                        }
                    }
                } catch (err) {
                    console.error('[openclaw-control] Error writing token file or updating .gitignore:', err)
                }
            }

            // Watch the directory so it works even before the file is created
            const watcher = fs.watch(path.dirname(controlFile), (_event, filename) => {
                if (filename !== 'openclaw-control.json') return
                try {
                    const raw = fs.readFileSync(controlFile, 'utf-8')
                    broadcast(server, JSON.parse(raw))
                } catch {
                    // file not ready yet or invalid JSON
                }
            })

            server.httpServer?.on('close', () => {
                watcher.close()
                try {
                    if (fs.existsSync(tokenFilePath)) {
                        fs.unlinkSync(tokenFilePath)
                    }
                } catch (err) {
                    console.error('[openclaw-control] Error removing temporary token file:', err)
                }
            })

            // HTTP endpoint so OpenClaw can POST commands directly
            server.middlewares.use('/api/control', (req, res, next) => {
                const origin = req.headers.origin ?? ''
                const allowedOrigin = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0]

                // Validate Origin header to prevent CSRF / DNS rebinding from unauthorized sources
                if (origin && !ALLOWED_ORIGINS.includes(origin)) {
                    res.writeHead(403)
                    res.end(JSON.stringify({ error: 'Forbidden origin' }))
                    return
                }

                if (req.method === 'OPTIONS') {
                    res.setHeader('Access-Control-Allow-Origin', allowedOrigin)
                    res.setHeader('Vary', 'Origin')
                    res.setHeader('Access-Control-Allow-Methods', 'POST')
                    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization')
                    res.writeHead(204)
                    res.end()
                    return
                }

                if (req.method !== 'POST') return next()

                // Rate limiting
                const clientIp = req.socket.remoteAddress ?? 'unknown'
                if (isRateLimited(clientIp)) {
                    res.writeHead(429)
                    res.end(JSON.stringify({ error: 'Too many requests' }))
                    return
                }

                // Token authentication
                const authHeader = req.headers.authorization ?? ''
                const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : ''
                if (token !== CONTROL_API_TOKEN) {
                    res.writeHead(401)
                    res.end(JSON.stringify({ error: 'Unauthorized' }))
                    return
                }

                res.setHeader('Access-Control-Allow-Origin', allowedOrigin)
                res.setHeader('Vary', 'Origin')
                res.setHeader('Content-Type', 'application/json')

                let body = ''
                req.on('data', (chunk: Buffer) => {
                    body += chunk
                    if (body.length > 4096) {
                        res.writeHead(413)
                        res.end(JSON.stringify({ error: 'Payload too large' }))
                        req.destroy()
                    }
                })
                req.on('end', () => {
                    try {
                        const command = JSON.parse(body) as Record<string, unknown>

                        // Validate command
                        const { command: cmd, value, id } = command
                        if (typeof cmd !== 'string' || !(cmd in COMMAND_VALIDATORS)) {
                            res.writeHead(400)
                            res.end(JSON.stringify({ error: 'Invalid command' }))
                            return
                        }
                        if (!COMMAND_VALIDATORS[cmd](value)) {
                            res.writeHead(400)
                            res.end(JSON.stringify({ error: 'Invalid value for command' }))
                            return
                        }
                        if (id !== undefined && typeof id !== 'string') {
                            res.writeHead(400)
                            res.end(JSON.stringify({ error: 'id must be a string' }))
                            return
                        }

                        broadcast(server, command)
                        res.writeHead(200)
                        res.end(JSON.stringify({ ok: true }))
                    } catch {
                        res.writeHead(400)
                        res.end(JSON.stringify({ error: 'Invalid JSON' }))
                    }
                })
            })
        },
    }
}

// Allowed proxy paths to prevent SSRF
const ALLOWED_PROXY_PATHS = ['/v1/chat/completions', '/v1/models']

// https://vite.dev/config/
export default defineConfig({
    plugins: [
        react(), 
        openClawControlPlugin(),
        obfuscatorPlugin({
            include: ['src/**/*.ts', 'src/**/*.tsx'],
            exclude: [/node_modules/],
            apply: 'build', // Only obfuscate on production build
            options: {
                compact: true,
                controlFlowFlattening: true,
                controlFlowFlatteningThreshold: 0.75,
                numbersToExpressions: true,
                simplify: true,
                stringArrayShuffle: true,
                splitStrings: true,
                stringArrayThreshold: 0.75
            }
        })
    ],
    build: {
        rollupOptions: {
            output: {
                manualChunks(id) {
                    if (!id.includes('node_modules')) return undefined
                    if (
                        id.includes('/three/') ||
                        id.includes('\\three\\') ||
                        id.includes('@react-three') ||
                        id.includes('three-stdlib')
                    ) {
                        return 'vendor-3d'
                    }
                    if (id.includes('@supabase')) return 'vendor-supabase'
                    if (
                        id.includes('/react/') ||
                        id.includes('\\react\\') ||
                        id.includes('react-dom') ||
                        id.includes('zustand')
                    ) {
                        return 'vendor-react'
                    }
                    return undefined
                },
            },
        },
        chunkSizeWarningLimit: 1200,
    },
    server: {
        host: '127.0.0.1',
        port: VITE_PORT,
        proxy: {
            '/v1': {
                target: `http://127.0.0.1:${OPENCLAW_LOCAL_PORT}`,
                changeOrigin: true,
                bypass(req) {
                    if (!ALLOWED_PROXY_PATHS.some(p => req.url?.startsWith(p))) {
                        return false
                    }
                    return undefined
                },
            },
        },
    },
})
